name: 02 - Evento issue
on:
  workflow_dispatch:
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: "say runner os name"
        run: echo "${{runner.os}}"
      - name: "say runner arch name"
        run: echo "${{runner.arch}}"