name: CI/CD Pipeline test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      step-1-status: ${{ steps.step1.outcome }}
      step-2-status: ${{ steps.step2.outcome }}
      step-3-status: ${{ steps.step3.outcome }}
    steps:
      - name: Step 1
        id: step1
        run: echo "Doing something..."

      - name: Step 2
        id: step2
        run: exit 1 # Simulando un fallo

      - name: Step 3
        id: step3
        run: echo "Doing something else..."

  summary:
    runs-on: ubuntu-latest
    needs: build
    if: always() # Asegúrate de que este job se ejecute siempre
    steps:
      - name: Generate Summary
        id: generate_summary
        run: |
          echo "## Summary of Steps" >> "$GITHUB_STEP_SUMMARY"
          
          if [ "${{ needs.build.outputs.step-1-status }}" == "success" ]; then
            echo "- [x] Step 1 - Completed" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- [ ] Step 1 - Failed" >> "$GITHUB_STEP_SUMMARY"
          
          
          if [ "${{ needs.build.outputs.step-2-status }}" == "success" ]; then
            echo "- [x] Step 2 - Completed" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- [ ] Step 2 - Failed" >> "$GITHUB_STEP_SUMMARY"
          
          
          if [ "${{ needs.build.outputs.step-3-status }}" == "success" ]; then
            echo "- [x] Step 3 - Completed" >> "$GITHUB_STEP_SUMMARY"
          else
            echo "- [ ] Step 3 - Failed" >> "$GITHUB_STEP_SUMMARY"