name: 08b - Control de flujo - funciones
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        version: [18, 20]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup node environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - run: npm ci
      - run: npm test
      - name: Forzar fallo
        run: exit 1
      - name: success
        if: ${{ success() }}  
        run: echo "success"
      - name: failure
        if: ${{ failure() }}  
        run: echo "failure"
      - name: always
        if: ${{ always() }}  
        run: echo "always"
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: despliegue
        run: echo "Desplegando en AWS..." 